"""[Auto-generated migration <entry.py>]

Revision ID: 0040b1716a64
Revises: f6c16f173aa3
Create Date: 2023-12-29 11:03:32.119076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0040b1716a64'
down_revision: Union[str, None] = 'f6c16f173aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
