"""[Auto-generated migration <entry.py>]

Revision ID: 0bc4d35add62
Revises: 361b9388549f
Create Date: 2023-12-29 11:03:10.198123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc4d35add62'
down_revision: Union[str, None] = '361b9388549f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
