"""[Auto-generated migration <entry.py>]

Revision ID: 0c5a09a80f54
Revises: bf2710882fb1
Create Date: 2023-12-29 11:03:12.639033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5a09a80f54'
down_revision: Union[str, None] = 'bf2710882fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
