"""[Auto-generated migration <entry.py>]

Revision ID: 103f213f91a1
Revises: a45390c6379b
Create Date: 2023-12-29 11:02:31.315156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103f213f91a1'
down_revision: Union[str, None] = 'a45390c6379b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
