"""[Auto-generated migration <entry.py>]

Revision ID: 115cee14bd59
Revises: ee1d1d39d3c7
Create Date: 2023-12-29 11:05:04.911516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115cee14bd59'
down_revision: Union[str, None] = 'ee1d1d39d3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
