"""[Auto-generated migration <entry.py>]

Revision ID: 13c6ad835218
Revises: ff4cffcd3f2a
Create Date: 2023-12-29 11:07:39.245951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c6ad835218'
down_revision: Union[str, None] = 'ff4cffcd3f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
