"""[Auto-generated migration <entry.py>]

Revision ID: 16937b0e9fb0
Revises: 97ecac2b2117
Create Date: 2023-12-29 11:07:30.623827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16937b0e9fb0'
down_revision: Union[str, None] = '97ecac2b2117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
