"""[Auto-generated migration <entry.py>]

Revision ID: 17f4ea63c175
Revises: 68e1f1e63c49
Create Date: 2023-12-29 11:07:42.383102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f4ea63c175'
down_revision: Union[str, None] = '68e1f1e63c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
