"""[Auto-generated migration <entry.py>]

Revision ID: 1826df8baa8d
Revises: d3e13cf3728b
Create Date: 2023-12-29 11:05:01.201176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1826df8baa8d'
down_revision: Union[str, None] = 'd3e13cf3728b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
