"""[Auto-generated migration <entry.py>]

Revision ID: 196815247cfb
Revises: d95bcd12c0cb
Create Date: 2023-12-29 11:02:59.399950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196815247cfb'
down_revision: Union[str, None] = 'd95bcd12c0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
