"""[Auto-generated migration <entry.py>]

Revision ID: 1b295dd391fc
Revises: c92d12ad7b06
Create Date: 2023-12-29 11:01:35.427973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b295dd391fc'
down_revision: Union[str, None] = 'c92d12ad7b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
