"""[Auto-generated migration <entry.py>]

Revision ID: 1d53e0c3f2c6
Revises: d0b483ec2693
Create Date: 2023-12-29 11:02:22.991053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d53e0c3f2c6'
down_revision: Union[str, None] = 'd0b483ec2693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
