"""[Auto-generated migration <entry.py>]

Revision ID: 1ff961dd44d0
Revises: 64d44ae96648
Create Date: 2023-12-29 11:03:29.905992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff961dd44d0'
down_revision: Union[str, None] = '64d44ae96648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
