"""[Auto-generated migration <entry.py>]

Revision ID: 22c0e515018d
Revises: 71f3820a43b3
Create Date: 2023-12-29 11:03:26.529535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c0e515018d'
down_revision: Union[str, None] = '71f3820a43b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
