"""[Auto-generated migration <entry.py>]

Revision ID: 230f59a7a283
Revises: 4e287c041c55
Create Date: 2023-12-29 11:02:30.003528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230f59a7a283'
down_revision: Union[str, None] = '4e287c041c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
