"""[Auto-generated migration <entry.py>]

Revision ID: 25ab1503dbd6
Revises: 839b647de4ec
Create Date: 2023-12-29 11:02:56.275337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ab1503dbd6'
down_revision: Union[str, None] = '839b647de4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
