"""[Auto-generated migration <entry.py>]

Revision ID: 2689222bca2b
Revises: 60af40275fde
Create Date: 2023-12-29 11:02:34.939096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2689222bca2b'
down_revision: Union[str, None] = '60af40275fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
