"""[Auto-generated migration <entry.py>]

Revision ID: 27506bb09483
Revises: ac9656de4f35
Create Date: 2023-12-29 11:04:58.458892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27506bb09483'
down_revision: Union[str, None] = 'ac9656de4f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
