"""[Auto-generated migration <entry.py>]

Revision ID: 28f810dfb26f
Revises: 8356f4a83444
Create Date: 2023-12-29 11:02:21.602982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f810dfb26f'
down_revision: Union[str, None] = '8356f4a83444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
