"""[Auto-generated migration <entry.py>]

Revision ID: 2d6e8bd4b2c5
Revises: da30a62dd519
Create Date: 2023-12-29 11:03:01.205565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6e8bd4b2c5'
down_revision: Union[str, None] = 'da30a62dd519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
