"""[Auto-generated migration <entry.py>]

Revision ID: 2fc96d87e41b
Revises: 985f1141292b
Create Date: 2023-12-29 11:03:15.756742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc96d87e41b'
down_revision: Union[str, None] = '985f1141292b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
