"""[Auto-generated migration <entry.py>]

Revision ID: 31a70e6d222e
Revises: 1b295dd391fc
Create Date: 2023-12-29 11:01:36.364816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a70e6d222e'
down_revision: Union[str, None] = '1b295dd391fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
