"""[Auto-generated migration <entry.py>]

Revision ID: 326e9fa4808e
Revises: 339e95ba7a66
Create Date: 2023-12-29 11:04:51.644096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326e9fa4808e'
down_revision: Union[str, None] = '339e95ba7a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
