"""[Auto-generated migration <entry.py>]

Revision ID: 361b9388549f
Revises: ebaf847d2d32
Create Date: 2023-12-29 11:03:09.290974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361b9388549f'
down_revision: Union[str, None] = 'ebaf847d2d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
