"""[Auto-generated migration <entry.py>]

Revision ID: 3a37af64e11d
Revises: 22c0e515018d
Create Date: 2023-12-29 11:03:27.436949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a37af64e11d'
down_revision: Union[str, None] = '22c0e515018d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
