"""[Auto-generated migration <entry.py>]

Revision ID: 3b4791971f0d
Revises: 6cf36f843857
Create Date: 2023-12-29 11:03:24.073415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4791971f0d'
down_revision: Union[str, None] = '6cf36f843857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
