"""[Auto-generated migration <entry.py>]

Revision ID: 3c31f17d987a
Revises: 1ff961dd44d0
Create Date: 2023-12-29 11:03:30.632794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c31f17d987a'
down_revision: Union[str, None] = '1ff961dd44d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
