"""[Auto-generated migration <entry.py>]

Revision ID: 3ea41a55312f
Revises: 91e64ab41ffe
Create Date: 2023-12-29 11:01:27.578394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea41a55312f'
down_revision: Union[str, None] = '91e64ab41ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
