"""[Auto-generated migration <entry.py>]

Revision ID: 4108c36d3c69
Revises: c5afc8f7bd89
Create Date: 2023-12-29 11:04:36.660763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4108c36d3c69'
down_revision: Union[str, None] = 'c5afc8f7bd89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
