"""[Auto-generated migration <entry.py>]

Revision ID: 421a7ff25743
Revises: f870dbd6ed7d
Create Date: 2023-12-29 11:02:42.433420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421a7ff25743'
down_revision: Union[str, None] = 'f870dbd6ed7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
