"""[Auto-generated migration <entry.py>]

Revision ID: 423780f2d16b
Revises: cf5756e2ec99
Create Date: 2023-12-29 11:02:28.193015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423780f2d16b'
down_revision: Union[str, None] = 'cf5756e2ec99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
