"""[Auto-generated migration <entry.py>]

Revision ID: 427cd2b18f39
Revises: 76b7d28e2e33
Create Date: 2023-12-29 11:04:49.439895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427cd2b18f39'
down_revision: Union[str, None] = '76b7d28e2e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
