"""[Auto-generated migration <entry.py>]

Revision ID: 43f557caf933
Revises: 427cd2b18f39
Create Date: 2023-12-29 11:04:50.113461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f557caf933'
down_revision: Union[str, None] = '427cd2b18f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
