"""[Auto-generated migration <entry.py>]

Revision ID: 4a1324acc82a
Revises: 63a939a7a3ac
Create Date: 2023-12-29 11:03:20.014887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1324acc82a'
down_revision: Union[str, None] = '63a939a7a3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
