"""[Auto-generated migration <entry.py>]

Revision ID: 4a53ec16a0c4
Revises: 22cccb9de03b
Create Date: 2023-12-29 11:01:32.590008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a53ec16a0c4'
down_revision: Union[str, None] = '22cccb9de03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
