"""[Auto-generated migration <entry.py>]

Revision ID: 4b42968a5bef
Revises: a90266c3a289
Create Date: 2023-12-29 11:01:30.075405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b42968a5bef'
down_revision: Union[str, None] = 'a90266c3a289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
