"""[Auto-generated migration <entry.py>]

Revision ID: 4e287c041c55
Revises: 423780f2d16b
Create Date: 2023-12-29 11:02:29.122698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e287c041c55'
down_revision: Union[str, None] = '423780f2d16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
