"""[Auto-generated migration <entry.py>]

Revision ID: 4e9ca18260e3
Revises: 103f213f91a1
Create Date: 2023-12-29 11:02:32.245331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9ca18260e3'
down_revision: Union[str, None] = '103f213f91a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
