"""[Auto-generated migration <entry.py>]

Revision ID: 5127ed8b46cd
Revises: 902d47fa0c31
Create Date: 2023-12-29 11:01:26.056258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5127ed8b46cd'
down_revision: Union[str, None] = '902d47fa0c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
