"""[Auto-generated migration <entry.py>]

Revision ID: 60af40275fde
Revises: a7f2de1045bc
Create Date: 2023-12-29 11:02:34.147044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60af40275fde'
down_revision: Union[str, None] = 'a7f2de1045bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
