"""[Auto-generated migration <entry.py>]

Revision ID: 612999e27ede
Revises: 890acd90f68d
Create Date: 2023-12-29 11:01:31.314271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612999e27ede'
down_revision: Union[str, None] = '890acd90f68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
