"""[Auto-generated migration <entry.py>]

Revision ID: 63a939a7a3ac
Revises: b1881d15558f
Create Date: 2023-12-29 11:03:19.159142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a939a7a3ac'
down_revision: Union[str, None] = 'b1881d15558f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
