"""[Auto-generated migration <entry.py>]

Revision ID: 642bed788e84
Revises: a64cd26515fa
Create Date: 2023-12-29 11:02:40.873856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642bed788e84'
down_revision: Union[str, None] = 'a64cd26515fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
