"""[Auto-generated migration <entry.py>]

Revision ID: 65f1554430dd
Revises: 0a1853a30365
Create Date: 2023-12-29 11:03:02.545683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f1554430dd'
down_revision: Union[str, None] = '0a1853a30365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
