"""[Auto-generated migration <entry.py>]

Revision ID: 68e1f1e63c49
Revises: 13c6ad835218
Create Date: 2023-12-29 11:07:40.732956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e1f1e63c49'
down_revision: Union[str, None] = '13c6ad835218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
