"""[Auto-generated migration <entry.py>]

Revision ID: 6b7a0a6c9db0
Revises: 7b0795bd9825
Create Date: 2023-12-29 11:02:57.844819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7a0a6c9db0'
down_revision: Union[str, None] = '7b0795bd9825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
