"""[Auto-generated migration <entry.py>]

Revision ID: 6d1dc9490e61
Revises: a27aa76014bb
Create Date: 2023-12-29 11:07:45.650849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1dc9490e61'
down_revision: Union[str, None] = 'a27aa76014bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
