"""[Auto-generated migration <entry.py>]

Revision ID: 6f32d8aa89fa
Revises: f2377bd6c357
Create Date: 2023-12-29 11:03:17.644350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f32d8aa89fa'
down_revision: Union[str, None] = 'f2377bd6c357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
