"""[Auto-generated migration <entry.py>]

Revision ID: 71f3820a43b3
Revises: a14caed1c694
Create Date: 2023-12-29 11:03:25.627753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f3820a43b3'
down_revision: Union[str, None] = 'a14caed1c694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
