"""[Auto-generated migration <entry.py>]

Revision ID: 746b4f736288
Revises: f20e294ff952
Create Date: 2023-12-29 11:04:55.331697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746b4f736288'
down_revision: Union[str, None] = 'f20e294ff952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
