"""[Auto-generated migration <entry.py>]

Revision ID: 785cc7840a16
Revises: 1826df8baa8d
Create Date: 2023-12-29 11:05:02.153289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785cc7840a16'
down_revision: Union[str, None] = '1826df8baa8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
