"""[Auto-generated migration <entry.py>]

Revision ID: 7b0795bd9825
Revises: 25ab1503dbd6
Create Date: 2023-12-29 11:02:56.954211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0795bd9825'
down_revision: Union[str, None] = '25ab1503dbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
