"""[Auto-generated migration <entry.py>]

Revision ID: 7bdec063b7b4
Revises: b41ef01889b8
Create Date: 2023-12-29 11:01:39.483848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bdec063b7b4'
down_revision: Union[str, None] = 'b41ef01889b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
