"""[Auto-generated migration <entry.py>]

Revision ID: 7d106ca438fe
Revises: 9e42e1d6f7c2
Create Date: 2023-12-29 11:02:49.480725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d106ca438fe'
down_revision: Union[str, None] = '9e42e1d6f7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
