"""[Auto-generated migration <entry.py>]

Revision ID: 7d26b306ea1c
Revises: b551cbbbda96
Create Date: 2023-12-29 11:01:28.838084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d26b306ea1c'
down_revision: Union[str, None] = 'b551cbbbda96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
