"""[Auto-generated migration <entry.py>]

Revision ID: 839b647de4ec
Revises: ad92f28d4284
Create Date: 2023-12-29 11:02:55.385435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839b647de4ec'
down_revision: Union[str, None] = 'ad92f28d4284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
