"""[Auto-generated migration <entry.py>]

Revision ID: 86106507d375
Revises: 3a37af64e11d
Create Date: 2023-12-29 11:03:28.108002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86106507d375'
down_revision: Union[str, None] = '3a37af64e11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
