"""[Auto-generated migration <entry.py>]

Revision ID: 88dd61bfd8fe
Revises: 326e9fa4808e
Create Date: 2023-12-29 11:04:52.507915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88dd61bfd8fe'
down_revision: Union[str, None] = '326e9fa4808e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
