"""[Auto-generated migration <entry.py>]

Revision ID: 890acd90f68d
Revises: 4b42968a5bef
Create Date: 2023-12-29 11:01:30.699712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890acd90f68d'
down_revision: Union[str, None] = '4b42968a5bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
