"""[Auto-generated migration <entry.py>]

Revision ID: 8c6aca35377e
Revises: 6d1dc9490e61
Create Date: 2023-12-29 11:07:47.363123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6aca35377e'
down_revision: Union[str, None] = '6d1dc9490e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
