"""[Auto-generated migration <entry.py>]

Revision ID: 8d5a72f7d5d8
Revises: 27506bb09483
Create Date: 2023-12-29 11:04:59.379168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5a72f7d5d8'
down_revision: Union[str, None] = '27506bb09483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
