"""[Auto-generated migration <entry.py>]

Revision ID: 902d47fa0c31
Revises: ab8fcfd8653d
Create Date: 2023-12-29 11:01:25.446651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902d47fa0c31'
down_revision: Union[str, None] = 'ab8fcfd8653d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
