"""[Auto-generated migration <entry.py>]

Revision ID: 9165505351f6
Revises: 88dd61bfd8fe
Create Date: 2023-12-29 11:04:53.180139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9165505351f6'
down_revision: Union[str, None] = '88dd61bfd8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
