"""[Auto-generated migration <entry.py>]

Revision ID: 918cfb35585b
Revises: 115cee14bd59
Create Date: 2023-12-29 11:05:05.841340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918cfb35585b'
down_revision: Union[str, None] = '115cee14bd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
