"""[Auto-generated migration <entry.py>]

Revision ID: 94a8ade64092
Revises: 5a2d242de120
Create Date: 2023-12-29 11:02:51.688879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a8ade64092'
down_revision: Union[str, None] = '5a2d242de120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
