"""[Auto-generated migration <entry.py>]

Revision ID: 957be820769a
Revises: 443ebb47dde0
Create Date: 2023-12-29 11:04:56.893401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957be820769a'
down_revision: Union[str, None] = '443ebb47dde0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
