"""[Auto-generated migration <entry.py>]

Revision ID: 96d7fe2e5512
Revises: 4a1324acc82a
Create Date: 2023-12-29 11:03:20.691937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d7fe2e5512'
down_revision: Union[str, None] = '4a1324acc82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
