"""[Auto-generated migration <entry.py>]

Revision ID: 985f1141292b
Revises: 7c2e3cc6bbb0
Create Date: 2023-12-29 11:03:15.109510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985f1141292b'
down_revision: Union[str, None] = '7c2e3cc6bbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
