"""[Auto-generated migration <entry.py>]

Revision ID: 98bae19ba3c3
Revises: 421a7ff25743
Create Date: 2023-12-29 11:02:43.301566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98bae19ba3c3'
down_revision: Union[str, None] = '421a7ff25743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
