"""[Auto-generated migration <entry.py>]

Revision ID: 9e42e1d6f7c2
Revises: 98bae19ba3c3
Create Date: 2023-12-29 11:02:44.230259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e42e1d6f7c2'
down_revision: Union[str, None] = '98bae19ba3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
