"""[Auto-generated migration <entry.py>]

Revision ID: a27aa76014bb
Revises: 17f4ea63c175
Create Date: 2023-12-29 11:07:44.044675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27aa76014bb'
down_revision: Union[str, None] = '17f4ea63c175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
