"""[Auto-generated migration <entry.py>]

Revision ID: a45390c6379b
Revises: 230f59a7a283
Create Date: 2023-12-29 11:02:30.611534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45390c6379b'
down_revision: Union[str, None] = '230f59a7a283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
