"""[Auto-generated migration <entry.py>]

Revision ID: a5862b16f83c
Revises: 88e49314feb9
Create Date: 2023-12-29 11:07:36.319202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5862b16f83c'
down_revision: Union[str, None] = '88e49314feb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
