"""[Auto-generated migration <entry.py>]

Revision ID: a64cd26515fa
Revises: c2a7a496a9d2
Create Date: 2023-12-29 11:02:39.925241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64cd26515fa'
down_revision: Union[str, None] = 'c2a7a496a9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
