"""[Auto-generated migration <entry.py>]

Revision ID: a90266c3a289
Revises: 7d26b306ea1c
Create Date: 2023-12-29 11:01:29.463742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90266c3a289'
down_revision: Union[str, None] = '7d26b306ea1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
