"""[Auto-generated migration <entry.py>]

Revision ID: ab8fcfd8653d
Revises: 3bf9a2e1b14c
Create Date: 2023-12-29 11:01:24.615904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8fcfd8653d'
down_revision: Union[str, None] = '3bf9a2e1b14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
