"""[Auto-generated migration <entry.py>]

Revision ID: ad92f28d4284
Revises: 15580a9d9c82
Create Date: 2023-12-29 11:02:54.715697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad92f28d4284'
down_revision: Union[str, None] = '15580a9d9c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
