"""[Auto-generated migration <entry.py>]

Revision ID: b1881d15558f
Revises: 6f32d8aa89fa
Create Date: 2023-12-29 11:03:18.511851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1881d15558f'
down_revision: Union[str, None] = '6f32d8aa89fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
