"""[Auto-generated migration <entry.py>]

Revision ID: b41ef01889b8
Revises: ff3dcd32f36e
Create Date: 2023-12-29 11:01:38.606363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41ef01889b8'
down_revision: Union[str, None] = 'ff3dcd32f36e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
