"""[Auto-generated migration <entry.py>]

Revision ID: b4faa8ee099b
Revises: 1d53e0c3f2c6
Create Date: 2023-12-29 11:02:23.805880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4faa8ee099b'
down_revision: Union[str, None] = '1d53e0c3f2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
