"""[Auto-generated migration <entry.py>]

Revision ID: b86af638654a
Revises: 8b60cc9e8603
Create Date: 2023-12-29 11:07:33.635377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86af638654a'
down_revision: Union[str, None] = '8b60cc9e8603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
