"""[Auto-generated migration <entry.py>]

Revision ID: ba2b9c8abae9
Revises: f6a32d78b83c
Create Date: 2023-12-29 11:01:41.428605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2b9c8abae9'
down_revision: Union[str, None] = 'f6a32d78b83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
