"""[Auto-generated migration <entry.py>]

Revision ID: bf2710882fb1
Revises: eb29c5c8e47c
Create Date: 2023-12-29 11:03:12.022525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2710882fb1'
down_revision: Union[str, None] = 'eb29c5c8e47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
