"""[Auto-generated migration <entry.py>]

Revision ID: c92d12ad7b06
Revises: e338b3071a34
Create Date: 2023-12-29 11:01:34.632409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92d12ad7b06'
down_revision: Union[str, None] = 'e338b3071a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
