"""[Auto-generated migration <entry.py>]

Revision ID: ccfc7b355b9a
Revises: 53f81710cfb0
Create Date: 2023-12-29 11:03:22.264842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfc7b355b9a'
down_revision: Union[str, None] = '53f81710cfb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
