"""[Auto-generated migration <entry.py>]

Revision ID: cf5756e2ec99
Revises: e16fbd278000
Create Date: 2023-12-29 11:02:27.287313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5756e2ec99'
down_revision: Union[str, None] = 'e16fbd278000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
