"""[Auto-generated migration <entry.py>]

Revision ID: d0b483ec2693
Revises: 28f810dfb26f
Create Date: 2023-12-29 11:02:22.264686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b483ec2693'
down_revision: Union[str, None] = '28f810dfb26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
