"""[Auto-generated migration <entry.py>]

Revision ID: d95bcd12c0cb
Revises: 6b7a0a6c9db0
Create Date: 2023-12-29 11:02:58.731566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95bcd12c0cb'
down_revision: Union[str, None] = '6b7a0a6c9db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
