"""[Auto-generated migration <entry.py>]

Revision ID: e16fbd278000
Revises: 6e84ea6c2b36
Create Date: 2023-12-29 11:02:26.345212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16fbd278000'
down_revision: Union[str, None] = '6e84ea6c2b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
