"""[Auto-generated migration <entry.py>]

Revision ID: e4008c7ebaf8
Revises: 785cc7840a16
Create Date: 2023-12-29 11:05:03.076089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4008c7ebaf8'
down_revision: Union[str, None] = '785cc7840a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
