"""[Auto-generated migration <entry.py>]

Revision ID: e96b518352e1
Revises: 7d106ca438fe
Create Date: 2023-12-29 11:02:50.126999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96b518352e1'
down_revision: Union[str, None] = '7d106ca438fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
