"""[Auto-generated migration <entry.py>]

Revision ID: eb29c5c8e47c
Revises: 0bc4d35add62
Create Date: 2023-12-29 11:03:11.141244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb29c5c8e47c'
down_revision: Union[str, None] = '0bc4d35add62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
