"""[Auto-generated migration <entry.py>]

Revision ID: ebaf847d2d32
Revises: 65f1554430dd
Create Date: 2023-12-29 11:03:08.580437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebaf847d2d32'
down_revision: Union[str, None] = '65f1554430dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
