"""[Auto-generated migration <entry.py>]

Revision ID: ee1d1d39d3c7
Revises: e4008c7ebaf8
Create Date: 2023-12-29 11:05:04.001094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1d1d39d3c7'
down_revision: Union[str, None] = 'e4008c7ebaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
