"""[Auto-generated migration <entry.py>]

Revision ID: f20e294ff952
Revises: 480ac1e7700c
Create Date: 2023-12-29 11:04:54.706550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20e294ff952'
down_revision: Union[str, None] = '480ac1e7700c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
