"""[Auto-generated migration <entry.py>]

Revision ID: f6a32d78b83c
Revises: 7bdec063b7b4
Create Date: 2023-12-29 11:01:40.501866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a32d78b83c'
down_revision: Union[str, None] = '7bdec063b7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
