"""[Auto-generated migration <entry.py>]

Revision ID: f870dbd6ed7d
Revises: 642bed788e84
Create Date: 2023-12-29 11:02:41.748741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f870dbd6ed7d'
down_revision: Union[str, None] = '642bed788e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
