"""[Auto-generated migration <entry.py>]

Revision ID: ff4cffcd3f2a
Revises: a5862b16f83c
Create Date: 2023-12-29 11:07:37.536520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4cffcd3f2a'
down_revision: Union[str, None] = 'a5862b16f83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
