# Set up server and mysql connection as docker-compose.yml

services:
  exchange:
    build: ./exchange
    depends_on:
      - mysql
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on: 
      - mysql
    volumes:
      - ./api:/usr/src/web
      - ./api/alembic/versions:/usr/src/web/api/alembic/versions
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql

  rq-dashboard:
    image: jaredv/rq-docker:0.0.2 
    command: rq-dashboard -H redis
    ports:
      - 9181:9181

  rq-worker:
    image: jaredv/rq-docker:0.0.2
    command: rq worker -u redis://redis:6379 high normal low
    deploy:
      replicas: 3